#ifndef CORE_STATES_HPP
#define CORE_STATES_HPP

enum class CoreState
{
    CORE_STATE_IDLE,
    CORE_STATE_WOKE,
    CORE_STATE_SOIL_HUMIDITY_CHECK,
    CORE_STATE_SOIL_PERIODIC_CHECK,
    CORE_STATE_IRRIGATE_SOIL,
    CORE_STATE_AIR_HUMIDITY_CHECK,
    CORE_STATE_AIR_PERIODIC_CHECK,
    CORE_STATE_IRRIGATE_AIR,
    CORE_STATE_WRAP_UP
};

#endif