pipeline {
	agent any
	
	stages {
		stage('Host build and test') {
			stages {
				stage('Host build') {
					steps {
						echo 'Build!'
						sh './scripts/host_build.sh'
					}
				}
				stage('Host test') {
					steps {
						echo 'Test!'
						sh './scripts/host_run_tests.sh'
					}
				}
			}
		}

        	stage('Target build and test') {
			stages {
				stage('Target build') {
					steps {
						echo 'Build!'
						sh './scripts/target_build.sh'
					}
				}
				stage('Target test') {
					steps {
						echo 'Test!'
					}
				}
			}
	        }
	}
}
