#ifndef ADC_DEFS_H
#define ADC_DEFS_H

typedef enum ADCIdentifierInternal
{
    IDENTIFIER_ADC0,
    IDENTIFIER_ADC1,
    IDENTIFIER_ADC2,
    IDENTIFIER_ADC3,
    IDENTIFIER_ADC4,
    IDENTIFIER_ADC5,
    IDENTIFIER_ADC6,
    IDENTIFIER_ADC7
} ADCIdentifier;

#endif